# Variáveis da Imagem
image:
  repository: acrfastfoodpostech.azurecr.io/fastfood/app:v1 
  migratorRepository: acrfastfoodpostech.azurecr.io/fastfood/migrator:v2
  pullPolicy: IfNotPresent

# Namespace customizável
namespace: fastfood

# Configurações do Service
service:
  type: ClusterIP  # ClusterIP para usar com AGIC
  port: 80

# Configurações do HPA
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuEnabled: true
  targetCPUUtilization: 70
  memoryEnabled: true
  targetMemoryUtilization: 75

# Variáveis do Azure PostgreSQL
postgres:
  host: "psql-fastfood-postech-001-lowcost-and.postgres.database.azure.com" # Host do Azure DB
  db: "fastfood" # Nome do DB
  port: "5432"

# Configurações do Ingress para AGIC
ingress:
  enabled: true
  host: "fastfood"
  ingressClassName: "azure-application-gateway"

credentials: 
  user: "adm" 
  password: "adm123" 