apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: db-data
  name: db-data
  namespace: fastfood
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 