apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastfood-app-hpa
  namespace: fastfood 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app 
  minReplicas: 1 
  maxReplicas: 5 
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 20